# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74a20eaa500ff62c63de1b9c724f901dd4218a8fbe31d039921021b96557b3ffaaa6a679679d19529ae175345c3376fbaa2e4748aae148ed3c99d1d0c69f79ac

test:
  secret_key_base: 42ed843fde2f0c7cdd3ef49511890d4e6f63eec8fce2aabb05c3baadef7147c716118b6dae0d3540bc5f764c482b6c6d74aea5b8790471e8b6a3d32b167ce452

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
